### ISSUE TITLE
Unable to create new pages

### ISSUE THREAD

**Issue by wmdbMattes** [addwiki/mediawiki-api#22]
Hi there,

first off, great tool, makes my live easier, thanks :)

Is it intended (or am I not getting it) that creating a new page is not possible?

**Comment by addshore** [comment]
I'm guessing you found the answer to this? :)

If I remember correctly you simply need to create an empty revision and save it! :)

**Comment by wmdbMattes** [comment]
The trick was to just supply a page title and omit the page ID.
I think I will try to make the PageIdentifier getting set automagically and send a PR.
